/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yamintun' at '1/28/17 9:50 PM' with Gradle 2.9
 *
 * @author yamintun, @date 1/28/17 9:50 PM
 */
import java.io.IOException;

public class FB {
    
	public static void main(String[] args) throws IOException{

		 //FacebookClient 
	}
	
}
