/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yamintun' at '1/28/17 9:50 PM' with Gradle 2.9
 *
 * @author yamintun, @date 1/28/17 9:50 PM
 */
import java.io.IOException;
import java.util.Scanner;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

public class Walkie {
    
	public static final String GOOGLE_SEARCH_URL = "https://www.google.com/search";
	public static final String FACEBOOK_SEARCH_URL = "https://facebook.com/search";
			//"https://graph.facebook.com/search";
	public static final int num_searches = 5;
	
	public static void search(String keyWord, String searchURL) throws IOException{
				
		Document doc = Jsoup.connect(searchURL).userAgent("Mozilla/5.0").get();
		
		Elements results = doc.select("h3.r > a");
		
		System.out.println(results + ", " + results.size());
		
		for(Element result: results){
			String linkHref = result.attr("href");
			String linkText = result.text();
			System.out.println("Text::"+linkText+ ", URL::"+ 
					linkHref.substring(6,  linkHref.indexOf("&")));
		}
	}
	
	public static void main(String[] args) throws IOException{
//		Scanner scanner = new Scanner(System.in);
//		System.out.println("Please enter search keyword.");
		
		String keyWord = "Wutt Hmone Thin Kyi"; //scanner.nextLine();
		String searchURL = GOOGLE_SEARCH_URL + "?q=" + keyWord + "&num=" + num_searches;
		search(keyWord, searchURL);
		
//		String target_name = "Wutt Hmone Thin Kyi";//scanner.nextLine();
//		String searchURL = FACEBOOK_SEARCH_URL + "?q=" + target_name;//"&type=user";
//		search(target_name, searchURL);

		//https://www.facebook.com/search/top/?q=mark%20zuckerberg
	}
	
}
